### PR TITLE
feat: new solutions upgrade

### PR DESCRIPTION
**Pull request by surajsbharadwaj**
### Description

1. Downgrade terraform ibm provider version to 1.49.0 to make it compatible with secure landing zone vpc module.
2. Reorganized the example folder structure
3. Upgraded the examples to have a full stack solution (secure landing zone vpc plus Powervs infra deployed in one go).
4. Renamed the flavour for IBM catalog

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [x] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

1. Downgrade terraform ibm provider version to 1.49.0 to make it compatible with secure landing zone vpc module.
2. Reorganized the example folder structure
3. Upgraded the examples to have a full stack solution (secure landing zone vpc plus Powervs infra deployed in one go).
4. Renamed the flavour for IBM catalog
5. Added json validation for powervs extension flavour

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Comment by surajsbharadwaj** [comment]
@kbiegert : could you please check the ibm_catalog.json file
@Beilmann could you please add in the necessary architecture diagrams, and readmes updated with right description.
@SirSpidey please help us in reviewing it.
Thank you

**Review by kbiegert — COMMENTED** [review]
in ibm_catalog.json you want to call out your dependency of slz on the extension flavor.  the fullstack looks correct to me.

**Comment by surajsbharadwaj** [comment]
invalid

**Review by Beilmann — APPROVED** [review]
@surajsbharadwaj - variation names (labels in ibm_catalog.json) should be discussed and - if needed - changed as separate PR.

**Pull request closed without merging**
