### PR TITLE
fix: "dependency_version_2": true

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

Catalog team are recommending to set `"dependency_version_2": true`. The UI will handle the way it displays dependencies better when enabled

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by surajsbharadwaj — APPROVED** [review]

**Comment by ocofaigh** [comment]
@surajsbharadwaj I'll let you handling merging, as I don't know if you wan't to generate a new release now or not

**Comment by ocofaigh** [comment]
@surajsbharadwaj maybe hold off on merge here - I found an issue. Will get back to you.

**Comment by ocofaigh** [comment]
Closing this for now - the catalog team need to provide migration support to move to this: https://github.ibm.com/ibmcloud/content-catalog/issues/5207

**Pull request closed without merging**
