### PR TITLE
docs: update variable descriptions

### PR DESCRIPTION
**Pull request by SirSpidey**
### Description

Make descriptions consistent. Some style and grammar updates.

**Check the relevant boxes:**
- [ ] Bug fix (nonbreaking change that fixes an issue)
- [ ] New feature (nonbreaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI related update (pipeline, etc.)

### Checklist

- [ ] If relevant, a test for the change has been added or updated as part of this PR.
- [ ] If relevant, documentation for the change has been added or updated as part of this PR.

### Merge

- Merge using "Squash and merge".
- Make sure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents. The commit message determines whether a new version of the modules needs to be released, and if so, which semver number to use).

### CODE REVIEW

**Comment by ocofaigh** [comment]
@SirSpidey I think you have an old version of common-dev-assets here. Can you run `git submodule update` and commit + push?

**Comment by SirSpidey** [comment]
@ocofaigh I had to run `git submodule update --remote --merge` to get any change to show up because I had already updated the submodule with the other command. Not sure if that's going to fix the issue or create new ones.

**Comment by ocofaigh** [comment]
Seems to be issues pulling the docker image used by pipeline. Have seen it in a few places today. Have restarted the pipeline to see if it works this time

**Comment by SirSpidey** [comment]
Closing this PR because I want to review the descriptions in related modules.

**Pull request closed without merging**
