### PR TITLE
Re-use secrets manager

### PR DESCRIPTION
**Pull request by alex-reiff**
### Description

Re-use existing SM instance during tests.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by surajsbharadwaj — APPROVED** [review]

**Comment by surajsbharadwaj** [comment]
@alex-reiff and @ocofaigh 
error:` CreateSecretWithContext failed The certificate template my-template couldn't be found. `

What's the value in your account ? and needs to be set in the tests

**Comment by alex-reiff** [comment]
```Error: [0m Error: [ERROR] Error while creating Load Balanacer Listener err The load balancer with ID 'r010-2b976f66-3582-4505-bf13-885b635dfc51' cannot be updated because its status is 'UPDATE_PENDING'.
```
Is this just a transient error?

**Pull request merged**
